name = "rooh1"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-01"

[assets]
directory = "./dist"

# --- التخزين (KV) ---
[[kv_namespaces]]
binding = "ROOH_KV"
id = "6d9110610f2c45b09c15d3f2f5dee50a"

# --- التخزين (R2) ---
[[r2_buckets]]
binding = "ROOH_BUCKET"
bucket_name = "roohme"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "roohme"

[[r2_buckets]]
binding = "ROOH_R2"
bucket_name = "roohme"

[[r2_buckets]]
binding = "roohme"
bucket_name = "roohme"

[[r2_buckets]]
binding = "REVIEWS_BUCKET"
bucket_name = "roohme"

# --- قواعد البيانات (D1) ---
[[d1_databases]]
binding = "h"
database_name = "h"
database_id = "8480585e-443f-4ef9-b4e4-45c941c9dbf1"

[[d1_databases]]
binding = "DB"
database_name = "h"
database_id = "8480585e-443f-4ef9-b4e4-45c941c9dbf1"

# --- المتغيرات ---
[vars]
SITE_URL = "https://roohpro.com"
SITE_BASE_URL = "https://roohpro.com"
ADMIN_EMAIL = "rooh10dodo@gmail.com"
ADMIN_PASSWORD = "5030775"
FIREBASE_PROJECT_ID = "ai-studio-7294fa8a-5970-449a-b8f3-b4a4511fcbc2"

# --- المراقبة ---
[observability]
enabled = true
