name = "discover-app"
account_id = "fa73541af4fcdd947ab78c12fe990a34"
main = "index.ts" 
compatibility_date = "2024-09-01"

# روابط الخدمات اللي ربطتها في كلاود فلير
[[services]]
binding = "rooh1"
service = "rooh1-service-name" 

[[services]]
binding = "pro"
service = "pro-service-name"   

[[services]]
binding = "topapp"
service = "topapp-service-name" 

# قواعد البيانات (D1)
[[d1_databases]]
binding = "h"
database_name = "h"
database_id = "8480585e-443f-4ef9-b4e4-45c941c9dbf1"

# التخزين (KV)
[[kv_namespaces]]
binding = "ROOH_KV"
id = "6d9110610f2c45b09c15d3f2f5dee50a"

# التخزين (R2)
[[r2_buckets]]
binding = "roohme"
bucket_name = "roohme"

[[r2_buckets]]
binding = "ROOH_R2"
bucket_name = "roohme"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "roohme"

[vars]
SITE_URL = "https://roohpro.com"
SITE_BASE_URL = "https://roohpro.com"
FIREBASE_PROJECT_ID = "ai-studio-remixremixremixr-f90e7953-c5a1-4541-b13d-95e6eb5f6d0b"